### PR TITLE
[WIP] Tfx cli 101

### PR DESCRIPTION
**Pull request by deep-diver**

### CODE REVIEW

**Comment by deep-diver** [comment]
How the second step looks like.

Screen Shot 2021-09-03 at 2 19 30 PM

**Comment by deep-diver** [comment]
How the second step looks like.

Screen Shot 2021-09-03 at 3 32 32 PM

**Comment by sayakpaul** [comment]
Yeah good idea to generate these beforehand!

If you are talking about setting up AI Platform Notebook instances then I think you could still refer them to existing materials. Several Codelabs do cover that step. I am mentioning this because that might help you to make the content even more compact yet precise.

**Comment by deep-diver** [comment]
@sayakpaul 

Done with the draft version. Please take a look. Below is the screenshots of each page.

**Page1:** https://ibb.co/19SQT2n
**Page2:** https://ibb.co/dmbRwPH
**Page3:** https://ibb.co/1LKzLYM
**Page4:** https://ibb.co/LCr5cmQ
**Page5:** https://ibb.co/8MX75BG

**Review by sayakpaul — APPROVED** [review]
@deep-diver looks fantastic! Do you want to also include the outputs of each of the steps involving the TFX CLI?

**Comment by deep-diver** [comment]
@sayakpaul 

sure! I will add the output after merging the PR. Thanks for your time to review on this!

**Pull request merged**
